name: Terraform Deploy

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:   # ✅ manual trigger only

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: self-hosted

    environment: staging

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init

      - run: terraform validate

      - run: terraform plan -out=tfplan

      - run: terraform apply -auto-approve tfplan
